apiVersion: apps/v1
kind: Deployment
metadata:
   name: devops-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
       app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: web
          image: nidhi460/devops-app:1.0
          ports:
            - containerPort: 80

